### ISSUE TITLE
TO-DO before the next release

### ISSUE THREAD

**Issue by Vaibhavs10** [Vaibhavs10/insanely-fast-whisper#23]
- [ ] Add FA2 support via `--fa2` parameter
- [ ] Add FA2 benchmarks 
- [ ] New release on PyPI
- [ ] Update the README to be more informative (add instructions to install, run, instructions on running without the CLI)
- [ ] Announce!
