### ISSUE TITLE
To-Do for the next release!

### ISSUE THREAD

**Issue by Vaibhavs10** [Vaibhavs10/insanely-fast-whisper#28]
- [ ] Add support for Large-v3 
- [ ] Update benchmarks
- [ ] Add a parameter for time-stamps
- [ ] Define usage and parameters better

cc: @patrick91 for vis!

**Comment by fcakyon** [comment]
Cant wait for the v3 support!

**Comment by Vaibhavs10** [comment]
This is now done!
https://x.com/reach_vb/status/1723810943329616007?s=20
